import React from 'react';
import {
  Arrow, TemarioContainer, Temas, Titulo, LeyendaEmpresa, ExtensionLeyendaEmpresa, ContenidoTemario,
} from './Temario.styled';
import ListaTemario from './ListaTemario';

class Temario extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isActive: false,
    };
  }

  render() {
    const temas = [
      {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      },
      {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      },
      {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      },
      {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      },,
      {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      }, {
        tipo: 'conDescripcion',
        id: 796,
        duracion: 'MEDIO',
        idDeAutor: 9,
        ultimoModificador: 'Ailen Muñoz',
        idDeReunion: 793,
        autor: 'Ailen Muñoz',
        prioridad: 2,
        titulo: 'HOla hola',
        descripcion: ':)',
        idsDeInteresados: [],
        obligatoriedad: 'OBLIGATORIO',
        idDePropuestaOriginal: null,
        fechaDePropuestaOriginal: null,
        esRePropuesta: false,
        linkDePresentacion: null,
        cantidadDeMinutosDelTema: 60,
      },
    ];


    return (
      <TemarioContainer isActive={this.state.isActive}>
        <Arrow src="./pino-blanco.svg" onMouseEnter={() => this.setState({ isActive: true })} />
        <Temas onMouseLeave={() => this.setState({ isActive: false })}>
          <LeyendaEmpresa>10 Pines</LeyendaEmpresa>
          <ExtensionLeyendaEmpresa>Creative Software Development</ExtensionLeyendaEmpresa>
          <ContenidoTemario>
            <Titulo> Temario </Titulo>
            <ListaTemario temas = {temas}
                        seleccionarTema = {this.props.seleccionarTema}/>
          </ContenidoTemario>
        </Temas>
      </TemarioContainer>
    );
  }
}

export default Temario;
